### PR TITLE
Altered as per the issue.

### PR DESCRIPTION
**Pull request by HassanAlthaf**
The issue can be found here: https://github.com/PatrickLouys/http/issues/9

### CODE REVIEW

**Comment by PatrickLouys** [comment]
Thanks for the effort, but the getParameter() Method should be kept working. There is also getParameters(). So there should also be a getQueryParameters() and get getBodyParameters() Method.

And don't forget the tests and interfaces... :) Travis CI build failed

**Comment by HassanAlthaf** [comment]
@PatrickLouys Alright, I will get them done for you fast, cuz I want this feature.

**Comment by HassanAlthaf** [comment]
There we go, build passed @PatrickLouys

**Comment by PatrickLouys** [comment]
Looking much better now, but I don't think it makes sense to keep get, post and the merged params stored. Instead the getters could handle the required logic.

Also would be sensible to rename the variables to getParameters and postParameters.

Unit tests for the new methods are still missing.

Thanks :)

**Comment by HassanAlthaf** [comment]
@PatrickLouys Feel free to merge, since it passes the test. :)

**Comment by PatrickLouys** [comment]
Thanks :)

**Comment by HassanAlthaf** [comment]
No problem mate. @PatrickLouys

**Pull request merged**
