### PR TITLE
add a public method send to avoid code duplicates

### PR DESCRIPTION
**Pull request by tflori**
Currently everyone using this response object has to write the code in his front controller. Instead we should give him this option - even if it is not testable.

### CODE REVIEW

**Comment by PatrickLouys** [comment]
I don't like this, if anything it should be a separate class. The response object should not have side effects.

This also would make it possible to call the send method multiple times, even from within a controller.

I would be open for having a new class or function which is responsible for dealing with the side effects, but I'm not sure about the best way to handle this. Doing it as it is right now makes it really flexible, for example we could also cache things.

**Comment by tflori** [comment]
With a not automagically called public methods there are not to expect side effects. Usually you will need to send the response when your app is finished. And the http class should know how to send the result to the browser.

Ok, we can add a condition (header not already sent) or a static that some response got already sent. But that is magic (why one method don't do what the method supposed to do) that should be left by the front controller.

That's the point. It is very flexible by give him the option to send this response. Is he sure to send this response? He don't need another response? Does this response has headers? Do we need to prepare the response? `$response->send()` because I don't know what to do...

I found this repo by your article about "developing without framework" and it is very easy and intuitiv. But to write three lines of code that is realated to this module is not that intuitiv. You don't write in your tutorial that I have to check `headers_sent()` so the controller (or handler) can already sent headers or text. It will fail for the same reason: you sent the response twice. And I agree with you: it is nothing we have to take care about - it's up to the developer not to sent headers when body already sent.

**Comment by PatrickLouys** [comment]
The response object is only a representation of the response data. Anything more would be a SRP violation.

So either write a separate class that sends the response to the browser, or just keep the three lines in the bootstrap file. You only have to write them once...

**Comment by tflori** [comment]
It is not. It is a question of the responsibility of the class. Is the class only responsible to gather data, or is the class responsible to send the response (yes, thats a single responsibility too) and needs to gather the data to send it.

I have to write them for n projects. And if something is changing for HTTP version 3 I have to change it in every project.

**Comment by PatrickLouys** [comment]
One class represents the data, another (optional) class sends the data. If you want to implement this, do it in a separate class. Any time that you need to use `and` to describe the responsibility of a class, you are violating SRP.

**Comment by tflori** [comment]
the responsibility is and is only: "send a response to the client". no `and` inside...

to be able to do this it needs the data. you can give the data by `addHeader`, `setContent` and so on. you can access the data by `getHeaders`, `getContent` and so on...

**Comment by PatrickLouys** [comment]
No. Building the response and sending it are two different responsibilites.

```
// this makes no sense, SRP violation
$responseSender->send();
$responseSender->setContent('foo);

// better
$response = new Response();
$response->setContent('foo');

$responseSender->send($response);
```

**Pull request closed without merging**
